baseURL = 'https://codingfox.dev/'
languageCode = 'en-us'
title = 'Coding Fox'
theme = 'ananke'

[params]
    github = 'https://github.com/LotharSpiegel'

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"