baseURL = 'https://codingfox.dev/'
languageCode = 'en-us'
title = 'Coding Fox'
theme = 'ananke'

[params]
    custom_css = ["css/syntax.css"]
    custom_js = ["js/copy-code-button.js"]
    github = 'https://github.com/LotharSpiegel'

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        noHl = false
        style = 'monokai'
        tabWidth = 4